### ISSUE TITLE
Add an ETH dashboard visualization to toggle between

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-explore-public#16]
- [x] Build the ETH version of the dashboard (done by @sui414) - http://dashboard.flashbots.net/public/dashboard/6103ee97-a978-4c57-b66e-44c4b1f44ba7
- [ ] Build toggle button to switch between both. I imagine something that looks like a 'dark mode button' that slides between ETH and USD at the top of the page? Wdyt?

**Comment by RyRy79261** [comment]
That link doesnt load when opened.

Which page are we referring to and how is USD being stipulated at the moment? 

Additionally, where would this button go on which page?

**Comment by obadiaa** [comment]
Just fixed the link! and answered in DM :)

Cranking out Metabase views now, will edit this comment with them once iz done
